import numpy as np
a = np.array([[100,200],[23,12]])
b = np.array([[10,20],[12,21]])
dot = np.dot(a,b)
print(dot)
vdot = np.vdot(a,b)
print(vdot)
inner = np.inner(a,b)
print(inner)
mul = np.matmul(a,b)
print(mul)
print(np.linalg.det(a))
print(np.linalg.solve(a, b))
c = np.linalg.inv(a)
print("Inverse:\n",c)